### ISSUE TITLE
Hubspot Beginner Task

### ISSUE THREAD

**Issue by shreythecray** [bitprj/onboarding#15]
# Contacting CS Clubs through Hubspot
## CS Clubs
- [x] Locate **Marketing University Outreach** Airtable
  - [x] Go to **University** tab > assign yourself 5 unassigned universities 
  - [x] Go to **Primary Table** tab
  - [x] Research + add new CS Student Organizations for assigned Universities to list
  - [x] Add contact information (email) for all
  - [x] Filter out organizations that you just added and download CSV of **Primary Table**
- [x] Create a Hubspot account
  - [x] Import CSV of CS Clubs emails into HubSpot
  - [x] Locate CS Clubs email template
  - [ ] Email blast all new CS organization emails

**Comment by minhtumn** [comment]
# Hubspot
## CS Clubs
- [ ] Locate Airtable w/ CS Clubs
  - [ ] Find/Add New CS Organizations from assigned Universities into Primary Table
  - [ ] Complete contact info for all new organizations
- [ ] Create a Hubspot account
  - [ ] Download CSV of Primary Table with only organizations from assigned universities
  - [ ] Import these CS Clubs emails into HubSpot
  - [ ] Locate CS Clubs email template
  - [ ] Email blast all new CS organization emails
