### ISSUE TITLE
Onboarding General Process 

### ISSUE THREAD

**Issue by beccatran** [bitprj/onboarding#2]
Please try to outline the onboarding process and answer these questions in the outline
- [x] Who is doing what in this onboarding process
- [x] How long will this take?
- [x] Where will be documented? 
- [x] What is the difference with Dev onboarding? 

I wrote out a very basic outline so feel free to enter steps in between. Be specific as much as you can, so we do not have to fully train someone else to do this and make sure to include all aspects such as the onboarding tasks, webinars, and etc.
- [x] Application is processed
- [x] Send automated email about “welcome to bit and please reserve a time on Daniel’s Calendly” ***figure out the time for this weekly meeting
- [x] Daniel’s introduction to sets expectations, introduces the objective, invites people to slack, and talk about being remote, Daniel refers them to their respective mentor/ director
- [x] Newbies have 1:1 with managers. Managers refer to the task and they have 7 days to finish the onboarding. Managers are responsible to add them on all the platforms that we are using
- [x] Newbies have to set another meeting with their respected managers to talk about the tasks and managers need to ask for their feedbacks 
- [x] Webinars

**Comment by minhtumn** [comment]
https://app.gitbook.com/@bit-project/s/bit-project/teams/developer-relations/joining-the-core-team
