### ISSUE TITLE
Writing Beginner Task

### ISSUE THREAD

**Issue by shreythecray** [bitprj/onboarding#44]
# Writing Beginner Task
*Please complete the following checklists and notify the Technical Writing Lead when you’re done.*

For ALL files:
- Copy the test file
- Push it into the repository
- Label it yourname_writingtest.md

## Checklist for case study file:
- [x] Grammar, punctuation, spelling check
- [x] Word count: 500-700, about 1.5 pages in Google Docs if you’re unsure
- [x] Include 2-5 sentence abstract about what you think the content is about
- [x] List of 3 strengths and 3 weaknesses you noticed when making changes; write brief explanation for all of them
- [x] Organizational and structural issues; this includes correcting any necessary formatting or citing of sources

## Checklist for **Curriculum** file:
- [x] Grammar, punctuation, spelling check
- [x] Word count: 650 words or less
- [x] Include 2-5 sentence abstract about what you think the content is about
- [x] List of 3 strengths and 3 weaknesses when making changes; write brief explanation for all of them
- [x] Organizational and structural issues; this includes correcting any necessary formatting or citing of sources

## Checklist for **About Us** website blurb:
- [x] Grammar, punctuation, spelling check
- [x] Word count: 60-75
- [x] Include 2-5 sentence abstract about what you think the content is about/what changes you made at top of file
- [x] List of 3 strengths and 3 weaknesses you noticed when making changes; write brief explanation for all of them
- [x] Organizational and structural issues; this includes correcting any necessary formatting or citing of sources

## Completion
- [x] Notify the Technical Writing Lead that you have completed this

**Comment by vkxu657** [comment]
https://github.com/bitprj/onboarding/issues/37#issuecomment-615056764
