### ISSUE TITLE
Vacancies

### ISSUE THREAD

**Issue by shreythecray** [bitprj/onboarding#5]
- [x] Create "Vacancies" folder in associated repo (DevRel, Marketing, People, Engineering)
- [x] Add files for various vacancies

Each file should include:
- Position name
- Brief description
- Qualifications
- Responsibilities
- Who to contact to apply

**Comment by lazyplatypus** [comment]
You don't need to add the who to contact to apply. I am finalizing the CMS on webflow for people folks to directly add positions *with a built in form* so no need for that the right person will be notified directly.

**Comment by lazyplatypus** [comment]
We should also Loop in DevRel Managers to add their vacancies here in addition to all of the dept/team leads :)

**Comment by lazyplatypus** [comment]
We should also Loop in DevRel Managers to add their vacancies here in addition to all of the dept/team leads :)
