### ISSUE TITLE
Zexing Fang

### ISSUE THREAD

**Issue by bryanwong8** [bitprj/onboarding#61]
# Engineer Onboarding Checklist

## Onboarding Lead Tasks: 

- [x] Tailor Email 
- [x] Contact Applicant(s) through Email
- [x] Create Zoom
- [x] Set-up Google Calendar Invite

### Day 0:
- [x] Watch [Getting Started at Bit Project](https://youtu.be/-jj090TR3po)
- [x] Ask for access to Bit Project Google Calendar 
- [x] Watch Webinars 
  - [x] [Communication in a Remote Workspace](https://www.youtube.com/watch?v=2f9TkttynIk)
  - [x] [Feedback](https://youtu.be/UlvYinqLsdo)
  - [x] [GitHub](https://youtu.be/NNrP1QCF1JE)
  - [x] [Diversity and Inclusion](https://youtu.be/dIvSjM-1Phw)
  - [x] Complete the [Webinar Quiz](https://airtable.com/shr31V9xdVRxOffMA)
- [x] Join Slack
- [x] Create GitHub account
- [x] Complete Welcome webinar (link will be provided)
*Note that this will be hosted everyone Monday. Please move on to the next steps if this does not occur on the first day of receiving tasks.

### Day 1:
- [x] Send Greeting into engineering-dept
      - Greeting Format:
      - Insert Introduction
      - Based from: insert city
      - Topics of interest: insert topics here
- [x] Attend Engineering Welcome Webinar
- [x] Schedule Team Meeting with Manager. The meeting must be within the next 2 days.

### Day 2-3: 
- [x] Meeting with Manager:
   * Breakdown of the Week (expectations)
  * Bit Project Introduction
  * Introduction to the team
      * How your workshop fits into the bigger picture
  * Discuss / Confirm Choice Topic & 3 or 5 week process
  * Discuss / Confirm Positions
  * Discuss / Confirm Deadlines

-[ ] Move on to Week 1 Procedures

### Day 4-5:

- [x] Complete 1:1 with Manager of Engineering  
  - [x] Understand the overview of the onboarding procedure 
  - [x] Breakdown of tasks and expectations for the first week 
  - [x] Understand what Engineering team does
  - [x] Practice taking notes on Github during the 1:1 
  - [x] Please give your overview feedback and express what position you are interested within the Engineering team!
  - [x] Give onboarding feedback

- [x] Attend Welcome Webinar (within you first week on onboarding)

**Comment by JersinFong** [comment]
done!
